In [3]:
# this is test code

In [14]:
a=10
b=40
a*b

400

In [17]:
import pandas as pd
data=[10,20,30,40]
s=pd.Series(data)
s

0    10
1    20
2    30
3    40
dtype: int64

In [19]:
import pandas as pd
data=[10,20,30,40]
s=pd.Series(data,index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [27]:
import pandas as pd
data=[10,20,30,40]
s=pd.Series(data)
(s.sum())

np.int64(100)

In [44]:
import pandas as pd
dict={"Name":['aman','sneha','alok'],
     "Marks":[20,30,40,],
     "City":['varanasi','kanpur','gaziput'],
     "Trade":['copa','fdt','fitter']
    }
df=pd.DataFrame(dict)

In [47]:
df.to_csv('data1.csv',index=False)

In [48]:
df.head(2)

    Name  Marks      City Trade
0   aman     20  varanasi  copa
1  sneha     30    kanpur   fdt

In [49]:
df.tail(2)

    Name  Marks     City   Trade
1  sneha     30   kanpur     fdt
2   alok     40  gaziput  fitter

In [60]:
df.loc[1,"Trade"]

'fdt'