In [3]:
import pandas as pd
dict={"name":['shakti','neha','ansh'],
      "makrs":[10,30,40],
       "city":['varanasi','obra','kanpur'],
        }
df=pd.DataFrame(dict)

     name  makrs      city
0  shakti     10  varanasi
1    neha     30      obra
2    ansh     40    kanpur

In [4]:
df.to_csv('data.csv',index=False)

In [5]:
df.head(2)

     name  makrs      city
0  shakti     10  varanasi
1    neha     30      obra

In [6]:
df.tail(2)

   name  makrs    city
1  neha     30    obra
2  ansh     40  kanpur

In [8]:
df.loc[1]

name     neha
makrs      30
city     obra
Name: 1, dtype: object

In [9]:
df.loc[1,"city"]

'obra'