In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data_text1.csv')

In [3]:
df

    Roll_No.     Name       Trade  Marks          City
0          1    Sneha        Copa     30        Vransi
1          2     aman      Fitter     50        Kanpur
2          3     alok  Electricen     40       Gazipur
3          4     arun        copa     35        Junpur
4          5    kajal      fitter     84      cholapur
5          6    mohit        copa     57  palahi patti
6          7  Vinayak  Electricen     69        Nahiya
7          8    Sanvi  Electricen     48      Sonbhadr
8          9     Abhi        copa     78        Baliya
9         10    Kavya        Copa     95       Magariy
10        11   Aayush      fitter     46      Varanasi
11        12     Ansh         NaN     76        Kanpur

In [4]:
len(df)

12

In [5]:
df.head(3)

   Roll_No.   Name       Trade  Marks     City
0         1  Sneha        Copa     30   Vransi
1         2   aman      Fitter     50   Kanpur
2         3   alok  Electricen     40  Gazipur

In [6]:
df.tail(3)

    Roll_No.    Name   Trade  Marks      City
9         10   Kavya    Copa     95   Magariy
10        11  Aayush  fitter     46  Varanasi
11        12    Ansh     NaN     76    Kanpur

In [13]:
df["Marks"].mean()

np.float64(59.0)

In [15]:
df["Marks"].max()

np.int64(95)

In [16]:
df["Marks"].min()

np.int64(30)

In [24]:
df["Marks"]

0     30
1     50
2     40
3     35
4     84
5     57
6     69
7     48
8     78
9     95
10    46
11    76
Name: Marks, dtype: int64

In [23]:
df[df["Marks"]==df["Marks"].max()]

   Roll_No.   Name Trade  Marks     City
9        10  Kavya  Copa     95  Magariy

In [67]:
df[df["Marks"]==df["Marks"].min()]

   Roll_No.   Name Trade  Marks    City
0         1  Sneha  Copa     30  Vransi

In [55]:
df[df["Trade"]=="Copa"]

   Roll_No.   Name Trade  Marks     City
0         1  Sneha  Copa     30   Vransi
9        10  Kavya  Copa     95  Magariy

In [60]:
len(df[df["Trade"]=="Electricen"])

3

In [66]:
df["Trade"].value_counts()

Trade
Electricen    3
copa          3
Copa          2
fitter        2
Fitter        1
Name: count, dtype: int64

In [69]:
df[df["Marks"]>80]

   Roll_No.   Name   Trade  Marks      City
4         5  kajal  fitter     84  cholapur
9        10  Kavya    Copa     95   Magariy

In [84]:
df.groupby("Trade")["Marks"].min()

Trade
Copa          30
Electricen    40
Fitter        50
copa          35
fitter        46
Name: Marks, dtype: int64

In [92]:
df.sort_values(by="Marks",ascending=False)

    Roll_No.     Name       Trade  Marks          City
9         10    Kavya        Copa     95       Magariy
4          5    kajal      fitter     84      cholapur
8          9     Abhi        copa     78        Baliya
11        12     Ansh         NaN     76        Kanpur
6          7  Vinayak  Electricen     69        Nahiya
5          6    mohit        copa     57  palahi patti
1          2     aman      Fitter     50        Kanpur
7          8    Sanvi  Electricen     48      Sonbhadr
10        11   Aayush      fitter     46      Varanasi
2          3     alok  Electricen     40       Gazipur
3          4     arun        copa     35        Junpur
0          1    Sneha        Copa     30        Vransi

In [98]:
df.sort_values(by="Marks",ascending=True)

    Roll_No.     Name       Trade  Marks          City
0          1    Sneha        Copa     30        Vransi
3          4     arun        copa     35        Junpur
2          3     alok  Electricen     40       Gazipur
10        11   Aayush      fitter     46      Varanasi
7          8    Sanvi  Electricen     48      Sonbhadr
1          2     aman      Fitter     50        Kanpur
5          6    mohit        copa     57  palahi patti
6          7  Vinayak  Electricen     69        Nahiya
11        12     Ansh         NaN     76        Kanpur
8          9     Abhi        copa     78        Baliya
4          5    kajal      fitter     84      cholapur
9         10    Kavya        Copa     95       Magariy

In [104]:
df["Marks"]=[10,52,20,25,33,17,81,80,99,100,38,22]

In [105]:
df

    Roll_No.     Name       Trade  Marks          City
0          1    Sneha        Copa     10        Vransi
1          2     aman      Fitter     52        Kanpur
2          3     alok  Electricen     20       Gazipur
3          4     arun        copa     25        Junpur
4          5    kajal      fitter     33      cholapur
5          6    mohit        copa     17  palahi patti
6          7  Vinayak  Electricen     81        Nahiya
7          8    Sanvi  Electricen     80      Sonbhadr
8          9     Abhi        copa     99        Baliya
9         10    Kavya        Copa    100       Magariy
10        11   Aayush      fitter     38      Varanasi
11        12     Ansh         NaN     22        Kanpur

In [108]:
df.loc[2,"Marks"]=[10]

In [107]:
df

    Roll_No.     Name       Trade  Marks          City
0          1    Sneha        Copa     10        Vransi
1          2     aman      Fitter     52        Kanpur
2          3     alok  Electricen     10       Gazipur
3          4     arun        copa     25        Junpur
4          5    kajal      fitter     33      cholapur
5          6    mohit        copa     17  palahi patti
6          7  Vinayak  Electricen     81        Nahiya
7          8    Sanvi  Electricen     80      Sonbhadr
8          9     Abhi        copa     99        Baliya
9         10    Kavya        Copa    100       Magariy
10        11   Aayush      fitter     38      Varanasi
11        12     Ansh         NaN     22        Kanpur